# This workflow is an example used during the Irish Dreamin'
# Agentforce DevOps: state of the art
# By @nabondance

name: Agentforce Script Release
# This workflow deploys Agentforce Script to selected org.
# It is split into several steps for better readability and understanding.

on:
  pull_request:
    types:
      - closed
    branches: [ main ]

jobs:
  setup-deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container: salesforce/cli:latest-slim

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: 'Scope project to agentforce-script'
        run: cp agentforce-script/sfdx-project.json sfdx-project.json

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install Dependencies
        id: pnpm-install
        run: pnpm install

      - name: 'Authenticate to destination org'
        run: |
         echo "${{ secrets.ORG_SFDX_AUTH_URL }}" > ./authfile
         sf org login sfdx-url --sfdxurlfile=authfile --alias=org

      - name: 'Deploy Agentforce Script to org'
        run: |
          sf project deploy start --target-org=org --manifest=agentforce-script/manifest.xml --wait=30

      - name: 'Publish Agentforce authoring bundles'
        run: bash agentforce-script/scripts/publishAgents.sh org

      - name: 'Activate Agentforce agents'
        run: bash agentforce-script/scripts/activateAgents.sh org
